namespace Capitan360.Application.Features.CompanyDomesticPaths.CompanyDomesticPathStructPrices.Commands.Update;

public record UpdateCompanyDomesticPathListStructPriceCommand(List<UpdateCompanyDomesticPathStructPriceItem> UpdateCompanyDomesticPathStructPriceItems);