namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.ChangeStateToReceivedAtSenderCompany;

public record ChangeStateCompanyDomesticWaybillToReceivedAtSenderCompanyCommand(int Id);
