namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.ChangeStateToReceivedAtSenderCompany;

public record ChangeStateToReceivedAtSenderCompanyCommand(int Id);
