namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybillPeriods.Commands.UpdateActiveState;

public record UpdateActiveStateCompanyDomesticWaybillPeriodCommand(int Id);
