namespace Capitan360.Application.Features.Companies.CompanyPreferenceses.Commands.UpdateIssueDomesticWaybillStateCompanyPreferences
{
    public record UpdateIssueDomesticWaybillStateCompanyPreferencesCommand(int Id);
}