namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.BackFormReceivedAtSenderCompanyState;

public record BackCompanyDomesticWaybillFromReceivedAtSenderCompanyStateCommand(int Id);

