namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.BackFormCollectiongState;

public record BackCompanyDomesticWaybillFromCollectiongStateCommand(int Id);
