namespace Capitan360.Application.Services.CompanyServices.CompanyDomesticPathCharge.Services;

public class CompanyDomesticPathChargeContentTypeService :  ICompanyDomesticPathChargeContentTypeService
{
}