namespace Capitan360.Application.Features.CompanyManifestForms.CompanyManifestForms.Commands.ChangeStateToAirlineDelivery;

public record ChangeStateCompanyManifestFormToAirlineDeliveryCommand(int Id);
