namespace Capitan360.Application.Features.Companies.CompanyPreferenceses.Commands.UpdateInternationalAirlineCargoState;

public record UpdateInternationalAirlineCargoStateCompanyPreferencesCommand(int Id);
