namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.ChangeStateToBackToSenderCompany;

public record ChangeStateDomesticWaybillToBackToSenderCompanyCommand(int Id);
