namespace Capitan360.Application.Features.CompanyDomesticPaths.CompanyDomesticPathCharges.Commands.Create;

public record CreateCompanyDomesticPathChargeCommand(List<CreateCompanyDomesticPathChargeItemCommand> ChargeItems);