namespace Capitan360.Application.Features.Companies.CompanyDomesticPathCharges.Commands.Create;

public record CreateCompanyDomesticPathChargeCommand(List<CreateCompanyDomesticPathChargeItemCommand> ChargeItems);