namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.BackFromAirlineDeliveryState;

public record BackCompanyDomesticWaybillFromAirlineDeliveryStateCommand(int Id);

