namespace Capitan360.Application.Services.CompanyServices.CompanyDomesticPathStructPrice.Commands.Update;

public record UpdateCompanyDomesticPathListStructPriceCommand(List<UpdateCompanyDomesticPathStructPriceItem> UpdateCompanyDomesticPathStructPriceItems);