namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.BackFromDistributionState;

public record BackCompanyDomesticWaybillFromDistributionStateCommand(int Id);

