namespace Capitan360.Application.Features.CompanyDomesticPaths.CompanyDomesticPathCharges.Services;

public class CompanyDomesticPathChargeContentTypeService : ICompanyDomesticPathChargeContentTypeService
{
}