using Capitan360.Application.Common;
using Capitan360.Application.Services.CompanyServices.CompanyInsurance.CompanyInsurance.Commands.CreateCompanyInsurance;
using Capitan360.Application.Services.CompanyServices.CompanyInsurance.CompanyInsurance.Commands.DeleteCompanyInsurance;
using Capitan360.Application.Services.CompanyServices.CompanyInsurance.CompanyInsurance.Commands.UpdateActiveStateCompanyInsurance;
using Capitan360.Application.Services.CompanyServices.CompanyInsurance.CompanyInsurance.Commands.UpdateCompanyInsurance;
using Capitan360.Application.Services.CompanyServices.CompanyInsurance.CompanyInsurance.Queries.GetAllCompanyInsurances;
using Capitan360.Application.Services.CompanyServices.CompanyInsurance.CompanyInsurance.Queries.GetCompanyInsuranceByCompanyId;
using Capitan360.Application.Services.CompanyServices.CompanyInsurance.Dtos;

namespace Capitan360.Application.Services.CompanyServices.CompanyInsurance.CompanyInsurance.Services;

public interface ICompanyInsuranceService
{
    Task<ApiResponse<int>> CreateCompanyInsuranceAsync(CreateCompanyInsuranceCommand createCompanyInsuranceCommand, CancellationToken cancellationToken);

    Task<ApiResponse<int>> DeleteCompanyInsuranceAsync(DeleteCompanyInsuranceCommand deleteCompanyInsuranceCommand, CancellationToken cancellationToken);

    Task<ApiResponse<int>> SetCompanyInsuranceActivityStatusAsync(UpdateActiveStateCompanyInsuranceCommand updateActiveStateCompanyInsuranceCommand, CancellationToken cancellationToken);

    Task<ApiResponse<CompanyInsuranceDto>> UpdateCompanyInsuranceAsync(UpdateCompanyInsuranceCommand updateCompanyInsuranceCommand, CancellationToken cancellationToken);

    Task<ApiResponse<PagedResult<CompanyInsuranceDto>>> GetAllCompanyInsurancesAsync(GetAllCompanyInsurancesQuery getAllCompanyInsurancesQuery, CancellationToken cancellationToken);

    Task<ApiResponse<CompanyInsuranceDto>> GetCompanyInsuranceByCompanyIdAsync(GetCompanyInsuranceByCompanyIdQuery getCompanyInsuranceByCompanyIdQuery, CancellationToken cancellationToken);

    Task<ApiResponse<CompanyInsuranceDto>> GetCompanyInsuranceByIdAsync(GetCompanyInsuranceByIdQuery getCompanyInsuranceByIdQuery, CancellationToken cancellationToken);
}