namespace Capitan360.Application.Features.CompanyDomesticPaths.CompanyDomesticPathReceiverCompanies.Queries.GetByDomesticPathId;

public record GetCompanyDomesticPathReceiverCompanyByDomesticPathIdQuery(int DomesticPathId);
