namespace Capitan360.Application.Features.CompanyManifestForms.CompanyManifestForms.Commands.BackFromReceivedAtReceiverCompanyState;

public record BackCompanyManifestFormFromReceivedAtReceiverCompanyStateCommand(int Id);
