namespace Capitan360.Application.Features.CompanyManifestForms.CompanyManifestForms.Commands.ChangeStateToAirlineDeliveryFromDesktop;

public record ChangeStateToAirlineDeliveryFromDesktopCommand(
long No,
string CompanySenderCaptain360Code
);
