namespace Capitan360.Application.Features.CompanyManifestForms.CompanyManifestForms.Commands.ChangeStateToReceivedAtReceiverCompanyFromDesktop;

public record ChangeStateToReceivedAtReceiverCompanyFromDesktopCommand(
long No,
string CompanyReceiverCaptain360Code
);
