namespace Capitan360.Application.Services.CompanyServices.CompanyPreferences.Commands.CreateCompanyPreferences;

public record CreateCompanyPreferencesCommand(
    int CompanyId,
    string EconomicCode,
    string NationalId,
    string RegistrationId,
    string CaptainCargoName,
    string CaptainCargoCode,
    decimal Tax,
    bool ActiveIssueDomesticWaybill = false,
    bool ActiveShowInSearchEngine = false,
    bool ActiveInWebServiceSearchEngine = false,
    bool ActiveInternationalAirlineCargo = false,
    bool ExitStampBillMinWeightIsFixed = false,
    bool ExitPackagingMinWeightIsFixed = false,
    bool ExitAccumulationMinWeightIsFixed = false,
    bool ExitExtraSourceMinWeightIsFixed = false,
    bool ExitPricingMinWeightIsFixed = false,
    bool ExitRevenue1MinWeightIsFixed = false,
    bool ExitRevenue2MinWeightIsFixed = false,
    bool ExitRevenue3MinWeightIsFixed = false,
    bool ExitFareInTax = false,
    bool ExitStampBillInTax = false,
    bool ExitPackagingInTax = false,
    bool ExitAccumulationInTax = false,
    bool ExitExtraSourceInTax = false,
    bool ExitPricingInTax = false,
    bool ExitRevenue1InTax = false,
    bool ExitRevenue2InTax = false,
    bool ExitRevenue3InTax = false,
    bool ExitDistributionInTax = false,
    bool ExitExtraDestinationInTax = false);