namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.BackFromReceivedAtReceiverCompanyState;

public record BackCompanyDomesticWaybillFromReceivedAtReceiverCompanyStateCommand(int Id);

