namespace Capitan360.Application.Features.CompanyManifestForms.CompanyManifestForms.Commands.ChangeStateToReceivedAtReceiverCompany;

public record ChangeStateToReceivedAtReceiverCompanyCommand(int Id);
