namespace Capitan360.Application.Features.Companies.CompanyPreferenceses.Commands.UpdateWebServiceSearchEngineState;

public record UpdateWebServiceSearchEngineStateCompanyPreferencesCommand(int Id);
