namespace Capitan360.Application.Features.CompanyDomesticPaths.CompanyDomesticPathCharges.Commands.Update;

public record UpdateCompanyDomesticPathChargeCommand(List<UpdateCompanyDomesticPathChargeItemCommand> ChargeItems);