using Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybillPackageTypes.Dtos;

namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.UpdateDomesticWaybill;

public record UpdateDomesticWaybillCommand(
    int? CompanyReceiverId,
    string? CompanyReceiverCaptain360Code,
    string? CompanyReceiverCaptain360Name,
    int? SourceMunicipalAreaId,
    decimal? SourceLatitude,
    decimal? SourceLongitude,
    string StopCityName,
    int? DestinationMunicipalAreaId,
    decimal? DestinationLatitude,
    decimal? DestinationLongitude,
    int? InsuranceCompanyId,
    decimal GrossWeight,
    decimal DimensionalWeight,
    decimal ChargeableWeight,
    int WeightCount,
    int Rate,
    decimal CompanyDomesticWaybillTax,
    long ExitFare,
    long ExitStampBill,
    long ExitPackaging,
    long ExitAccumulation,
    long ExitDistribution,
    long ExitExtraSource,
    long ExitExtraDestination,
    long ExitPricing,
    long ExitRevenue1,
    long ExitRevenue2,
    long ExitRevenue3,
    long ExitTaxCompanySender,
    long ExitTaxCompanyReceiver,
    long ExitInsuranceCost,
    long ExitTaxInsuranceCost,
    long ExitInsuranceCostGain,
    long ExitTaxInsuranceCostGain,
    long ExitDiscount,
    long ExitTotalCost,
    string HandlingInformation,
    string FlightNo,
    string FlightDate,
    string CompanySenderDateFinancial,
    bool CompanySenderCashPayment,
    bool CompanySenderCashOnDelivery,
    bool CompanySenderBankPayment,
    int? CompanySenderBankId,
    string CompanySenderBankPaymentNo,
    bool CompanySenderCreditPayment,
    string CustomerPanelId,
    string CustomerSenderNameFamily,
    string CustomerSenderMobile,
    string CustomerSenderAddress,
    short TypeOfFactorInSamanehMoadianId,
    string CustomerSenderNationalCode,
    string CustomerSenderEconomicCode,
    string CustomerSenderNationalID,
    string CustomerReceiverNameFamily,
    string CustomerReceiverMobile,
    string CustomerReceiverAddress,
    string DescriptionSenderCompany,
    string DescriptionSenderCustomer,
    List<CompanyDomesticWaybillPackageTypeDto> CompanyDomesticWaybillPackageTypes
    )
{
    public int Id { get; set; }
};

