namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Commands.ChangeStateToReceivedAtReceiverCompany;

public record ChangeStateCompanyDomesticWaybillToReceivedAtReceiverCompanyCommand(int Id);
