using Capitan360.Domain.Enums;

namespace Capitan360.Application.Features.CompanyDomesticWaybills.CompanyDomesticWaybills.Dtos;

public class CompanyDomesticWaybillDto
{
    public int Id { get; set; }
    public long No { get; set; }
    public int CompanySenderId { get; set; }
    public string? CompanySenderName { get; set; }
    public int? CompanyReceiverId { get; set; }
    public string? CompanyReceiverName { get; set; }
    public string? CompanyReceiverUserInsertedCode { get; set; }
    public int SourceCountryId { get; set; }
    public string? SourceCountryName { get; set; }
    public int SourceProvinceId { get; set; }
    public string? SourceProvinceName { get; set; }
    public int SourceCityId { get; set; }
    public string? SourceCityName { get; set; }
    public int? SourceMunicipalAreaId { get; set; }
    public string? SourceMunicipalAreaName { get; set; }
    public decimal? SourceLatitude { get; set; }
    public decimal? SourceLongitude { get; set; }
    public string? StopCityName { get; set; }
    public int? DestinationCountryId { get; set; }
    public string? DestinationCountryName { get; set; }
    public int? DestinationProvinceId { get; set; }
    public string? DestinationProvinceName { get; set; }
    public int? DestinationCityId { get; set; }
    public string? DestinationCityName { get; set; }
    public int? DestinationMunicipalAreaId { get; set; }
    public string? DestinationMunicipalAreaName { get; set; }
    public decimal? DestinationLatitude { get; set; }
    public decimal? DestinationLongitude { get; set; }
    public int? CompanyDomesticWaybillPeriodId { get; set; }
    public string? CompanyDomesticWaybillPeriodCode { get; set; }
    public int? CompanyManifestFormId { get; set; }
    public string? CompanyManifestFormNo { get; set; }
    public int? CompanyInsuranceId { get; set; }
    public string? CompanyInsuranceName { get; set; }
    public decimal? GrossWeight { get; set; }
    public decimal? DimensionalWeight { get; set; }
    public decimal? ChargeableWeight { get; set; }
    public int? WeightCount { get; set; }
    public int? Rate { get; set; }
    public decimal? CompanyDomesticWaybillTax { get; set; }
    public long? ExitFare { get; set; }
    public long? ExitStampBill { get; set; }
    public long? ExitPackaging { get; set; }
    public long? ExitAccumulation { get; set; }
    public long? ExitDistribution { get; set; }
    public long? ExitExtraSource { get; set; }
    public long? ExitExtraDestination { get; set; }
    public long? ExitPricing { get; set; }
    public long? ExitRevenue1 { get; set; }
    public long? ExitRevenue2 { get; set; }
    public long? ExitRevenue3 { get; set; }
    public long? ExitTaxCompanySender { get; set; }
    public long? ExitTaxCompanyReceiver { get; set; }
    public long? ExitInsuranceCost { get; set; }
    public long? ExitTaxInsuranceCost { get; set; }
    public long? ExitInsuranceCostGain { get; set; }
    public long? ExitTaxInsuranceCostGain { get; set; }
    public long? ExitDiscount { get; set; }
    public long? EntranceDiscount { get; set; }
    public long? ExitTotalCost { get; set; }
    public string? HandlingInformation { get; set; }
    public string? FlightNo { get; set; }
    public string? FlightDate { get; set; }
    public string? CompanySenderDateFinancial { get; set; }
    public bool? CompanySenderCashPayment { get; set; }
    public bool? CompanySenderCashOnDelivery { get; set; }
    public bool? CompanySenderBankPayment { get; set; }
    public int? CompanySenderBankId { get; set; }
    public string? CompanySenderBankName { get; set; }
    public string? CompanySenderBankPaymentNo { get; set; }
    public bool? CompanySenderCreditPayment { get; set; }
    public string? CustomerPanelId { get; set; }
    public string? CustomerPanelNameFamily { get; set; }
    public string? CompanyReceiverDateFinancial { get; set; }
    public bool? CompanyReceiverCashPayment { get; set; }
    public bool? CompanyReceiverBankPayment { get; set; }
    public bool? CompanyReceiverCashOnDelivery { get; set; }
    public int? CompanyReceiverBankId { get; set; }
    public string? CompanyReceiverBankName { get; set; }
    public string? CompanyReceiverBankPaymentNo { get; set; }
    public bool? CompanyReceiverCreditPayment { get; set; }
    public string? CompanyReceiverResponsibleCustomerId { get; set; }
    public string? CompanyReceiverResponsibleCustomerNameFamily { get; set; }
    public string? CustomerSenderNameFamily { get; set; }
    public string? CustomerSenderMobile { get; set; }
    public string? CustomerSenderAddress { get; set; }
    public short? TypeOfFactorInSamanehMoadianId { get; set; }
    public MoadianFactorType? TypeOfFactorInSamanehMoadian { get; set; }
    public string? CustomerSenderNationalCode { get; set; }
    public string? CustomerSenderEconomicCode { get; set; }
    public string? CustomerSenderNationalID { get; set; }
    public string? CustomerReceiverNameFamily { get; set; }
    public string? CustomerReceiverMobile { get; set; }
    public string? CustomerReceiverAddress { get; set; }
    public short State { get; set; }
    public CompanyDomesticWaybillState WaybillSate { get; set; }
    public string? DateIssued { get; set; }
    public string? TimeIssued { get; set; }
    public string? DateCollectiong { get; set; }
    public string? TimeCollectiong { get; set; }
    public string? BikeDeliveryInSenderCompanyId { get; set; }
    public string? BikeDeliveryInSenderCompanyNameFamily { get; set; }
    public string? BikeDeliveryInSenderCompanyAgent { get; set; }
    public string? DateReceivedAtSenderCompany { get; set; }
    public string? TimeReceivedAtSenderCompany { get; set; }
    public string? DateManifested { get; set; }
    public string? TimeManifested { get; set; }
    public string? DateAirlineDelivery { get; set; }
    public string? TimeAirlineDelivery { get; set; }
    public string? DateReceivedAtReceiverCompany { get; set; }
    public string? TimeReceivedAtReceiverCompany { get; set; }
    public string? DateDistribution { get; set; }
    public string? TimeDistribution { get; set; }
    public string? BikeDeliveryInReceiverCompanyId { get; set; }
    public string? BikeDeliveryInReceiverCompanyNameFamily { get; set; }
    public string? BikeDeliveryInReceiverCompanyAgent { get; set; }
    public string? DateDelivery { get; set; }
    public string? TimeDelivery { get; set; }
    public string? EntranceDeliveryPerson { get; set; }
    public string? EntranceTransfereePersonName { get; set; }
    public string? EntranceTransfereePersonNationalCode { get; set; }
    public string? DescriptionSenderCompany { get; set; }
    public string? DescriptionReceiverCompany { get; set; }
    public string? DescriptionSenderCustomer { get; set; }
    public string? DescriptionReceiverCustomer { get; set; }
    public bool? Lock { get; set; }
    public bool? IsIssueFromCaptainCargoWebSite { get; set; }
    public bool? IsIssueFromCompanyWebSite { get; set; }
    public bool? IsIssueFromCaptainCargoWebService { get; set; }
    public bool? IsIssueFromCompanyWebService { get; set; }
    public bool? IsIssueFromCaptainCargoPanel { get; set; }
    public bool? IsIssueFromCaptainCargoDesktop { get; set; }
    public long? CaptainCargoPrice { get; set; }
    public string? CounterId { get; set; }
    public string? CounterNameFamily { get; set; }
    public bool? Dirty { get; set; }
}
