using Capitan360.Application.Common;
using Capitan360.Application.Services.CompanyServices.CompanyDomesticPath.Commands.CreateCompanyDomesticPath;
using Capitan360.Application.Services.CompanyServices.CompanyDomesticPath.Commands.DeleteCompanyDomesticPath;
using Capitan360.Application.Services.CompanyServices.CompanyDomesticPath.Commands.UpdateActiveStateCompanyDomesticPath;
using Capitan360.Application.Services.CompanyServices.CompanyDomesticPath.Commands.UpdateCompanyDomesticPath;
using Capitan360.Application.Services.CompanyServices.CompanyDomesticPath.Dtos;
using Capitan360.Application.Services.CompanyServices.CompanyDomesticPath.Queries.GetAllCompanyDomesticPaths;
using Capitan360.Application.Services.CompanyServices.CompanyDomesticPath.Queries.GetCompanyDomesticPathByCompanyId;
using Capitan360.Application.Services.CompanyServices.CompanyDomesticPath.Queries.GetCompanyDomesticPathById;

namespace Capitan360.Application.Services.CompanyServices.CompanyDomesticPath.Services;

public interface ICompanyDomesticPathsService
{
    Task<ApiResponse<int>> CreateCompanyDomesticPathAsync(CreateCompanyDomesticPathCommand createCompanyDomesticPathCommand, CancellationToken cancellationToken);

    Task<ApiResponse<int>> DeleteCompanyDomesticPathAsync(DeleteCompanyDomesticPathCommand deleteCompanyDomesticPathCommand, CancellationToken cancellationToken);

    Task<ApiResponse<int>> SetCompanyDomesticPathActivityStatusAsync(UpdateActiveStateCompanyDomesticPathCommand updateActiveStateCompanyDomesticPathCommand, CancellationToken cancellationToken);

    Task<ApiResponse<CompanyDomesticPathDto>> UpdateCompanyDomesticPathAsync(UpdateCompanyDomesticPathCommand updateCompanyDomesticPathCommand, CancellationToken cancellationToken);

    Task<ApiResponse<PagedResult<CompanyDomesticPathDto>>> GetAllCompanyDomesticPathsAsync(GetAllCompanyDomesticPathsQuery getAllCompanyDomesticPathsQuery, CancellationToken cancellationToken);

    Task<ApiResponse<CompanyDomesticPathDto>> GetCompanyDomesticPathByCompanyIdAsync(GetCompanyDomesticPathByCompanyIdQuery getCompanyDomesticPathByCompanyIdQuery, CancellationToken cancellationToken);

    Task<ApiResponse<CompanyDomesticPathDto>> GetCompanyDomesticPathByIdAsync(GetCompanyDomesticPathByIdQuery getCompanyDomesticPathByIdQuery, CancellationToken cancellationToken);
}