namespace Capitan360.Application.Features.CompanyManifestForms.CompanyManifestForms.Commands.BackFromAirlineDeliveryState;

public record BackCompanyManifestFormFromAirlineDeliveryStateCommand(int Id);
